import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import btnStyles from '@/styles/button.module.css';
import Link from 'next/link'
import { useState } from 'react'
import Axios from 'axios';

const inter = Inter({ subsets: ['latin'] })

export default function Home()
{
  const [reviewed, setReviewed] = useState(false);

  const [review, setReview] = useState('');

  const handleSubmit = () =>
  {
    setReviewed(true);
    Axios.post("http://localhost:3000/api/reviews", {
      review: review,
    }).then()
  }

  return (
    <>
      <Head>
        <title>Doe's Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {!reviewed && <div className={`${styles.beforeAction} ${styles.container}`}>
          <h1 style={{fontSize: 32, fontStyle: 'italic'}}>Doe's Restaurant</h1>
          <div>
            <h1 style={{fontSize: 24}}>Review Our Food</h1>
            <textarea value={review} name="review" id="review" className={`${styles.textarea}`} onChange={(e) => setReview(e.target.value)}/>
          </div>
          <button onClick={handleSubmit} className={`${btnStyles.btn}`}>Submit</button>
        </div>
        }
        {reviewed && <div className={`${styles.afterAction} ${styles.container}`}>
          <h1>Thank You for Your Review</h1>
          <Link href={"./reviews"}><button className={`${btnStyles.btn}`}>See Our Reviews</button></Link>
        </div>
        }
      </main>
    </>
  )
}
